apiVersion: apps/v1
kind: Deployment
metadata:
  name: cookbook
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cookbook
  template:
    metadata:
      labels:
        app: cookbook
    spec:
      containers:
        - name: cookbook
          image: mateuslopess/cookbook:latest
          ports:
            - containerPort: 5173