apiVersion: v1
kind: Service
metadata:
  name: cookbook-service
spec:
  type: NodePort
  selector:
    app: cookbook
  ports:
    - protocol: TCP
      port: 5173
      targetPort: 5173
      nodePort: 30000