apiVersion: v1
kind: Service
metadata:
  name: cookbook-service
spec:
  selector:
    app: cookbook
  ports:
    - protocol: TCP
      port: 9000          # porta do service (client acessa aqui)
      targetPort: 5173    # porta do container (onde app está ouvindo)
  type: NodePort
